insert into information_schema.INNODB_INDEXES (INDEX_ID, NAME, TABLE_ID, TYPE, N_FIELDS, PAGE_NO, SPACE, MERGE_THRESHOLD) values (172, 'PRIMARY', 1088, 3, 5, 4, 31, 50);
insert into information_schema.INNODB_INDEXES (INDEX_ID, NAME, TABLE_ID, TYPE, N_FIELDS, PAGE_NO, SPACE, MERGE_THRESHOLD) values (171, 'GEN_CLUST_INDEX', 1087, 1, 14, 4, 30, 50);
insert into information_schema.INNODB_INDEXES (INDEX_ID, NAME, TABLE_ID, TYPE, N_FIELDS, PAGE_NO, SPACE, MERGE_THRESHOLD) values (168, 'GEN_CLUST_INDEX', 1084, 1, 31, 4, 27, 50);
insert into information_schema.INNODB_INDEXES (INDEX_ID, NAME, TABLE_ID, TYPE, N_FIELDS, PAGE_NO, SPACE, MERGE_THRESHOLD) values (170, 'GEN_CLUST_INDEX', 1086, 1, 12, 4, 29, 50);
