insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'SELECT', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'INSERT', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'UPDATE', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'DELETE', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'CREATE', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'DROP', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'RELOAD', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'SHUTDOWN', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'PROCESS', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'FILE', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'REFERENCES', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'INDEX', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'ALTER', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'SHOW DATABASES', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'SUPER', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'CREATE TEMPORARY TABLES', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'LOCK TABLES', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'EXECUTE', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'REPLICATION SLAVE', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'REPLICATION CLIENT', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'CREATE VIEW', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'SHOW VIEW', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'CREATE ROUTINE', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'ALTER ROUTINE', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'CREATE USER', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'EVENT', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'TRIGGER', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'CREATE TABLESPACE', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'CREATE ROLE', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'DROP ROLE', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'APPLICATION_PASSWORD_ADMIN', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'AUDIT_ADMIN', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'BACKUP_ADMIN', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'BINLOG_ADMIN', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'BINLOG_ENCRYPTION_ADMIN', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'CLONE_ADMIN', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'CONNECTION_ADMIN', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'ENCRYPTION_KEY_ADMIN', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'GROUP_REPLICATION_ADMIN', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'INNODB_REDO_LOG_ARCHIVE', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'PERSIST_RO_VARIABLES_ADMIN', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'REPLICATION_APPLIER', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'REPLICATION_SLAVE_ADMIN', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'RESOURCE_GROUP_ADMIN', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'RESOURCE_GROUP_USER', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'ROLE_ADMIN', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'SERVICE_CONNECTION_ADMIN', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'SESSION_VARIABLES_ADMIN', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'SET_USER_ID', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'SYSTEM_USER', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'SYSTEM_VARIABLES_ADMIN', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'TABLE_ENCRYPTION_ADMIN', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''caitlin''@''localhost''', 'def', 'XA_RECOVER_ADMIN', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''mysql.infoschema''@''localhost''', 'def', 'SELECT', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''mysql.session''@''localhost''', 'def', 'SHUTDOWN', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''mysql.session''@''localhost''', 'def', 'SUPER', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''mysql.session''@''localhost''', 'def', 'BACKUP_ADMIN', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''mysql.session''@''localhost''', 'def', 'CLONE_ADMIN', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''mysql.session''@''localhost''', 'def', 'CONNECTION_ADMIN', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''mysql.session''@''localhost''', 'def', 'PERSIST_RO_VARIABLES_ADMIN', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''mysql.session''@''localhost''', 'def', 'SESSION_VARIABLES_ADMIN', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''mysql.session''@''localhost''', 'def', 'SYSTEM_USER', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''mysql.session''@''localhost''', 'def', 'SYSTEM_VARIABLES_ADMIN', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''mysql.sys''@''localhost''', 'def', 'USAGE', 'NO');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'SELECT', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'INSERT', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'UPDATE', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'DELETE', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'CREATE', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'DROP', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'RELOAD', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'SHUTDOWN', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'PROCESS', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'FILE', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'REFERENCES', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'INDEX', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'ALTER', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'SHOW DATABASES', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'SUPER', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'CREATE TEMPORARY TABLES', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'LOCK TABLES', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'EXECUTE', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'REPLICATION SLAVE', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'REPLICATION CLIENT', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'CREATE VIEW', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'SHOW VIEW', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'CREATE ROUTINE', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'ALTER ROUTINE', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'CREATE USER', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'EVENT', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'TRIGGER', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'CREATE TABLESPACE', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'CREATE ROLE', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'DROP ROLE', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'APPLICATION_PASSWORD_ADMIN', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'AUDIT_ADMIN', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'BACKUP_ADMIN', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'BINLOG_ADMIN', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'BINLOG_ENCRYPTION_ADMIN', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'CLONE_ADMIN', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'CONNECTION_ADMIN', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'ENCRYPTION_KEY_ADMIN', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'GROUP_REPLICATION_ADMIN', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'INNODB_REDO_LOG_ARCHIVE', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'PERSIST_RO_VARIABLES_ADMIN', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'REPLICATION_APPLIER', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'REPLICATION_SLAVE_ADMIN', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'RESOURCE_GROUP_ADMIN', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'RESOURCE_GROUP_USER', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'ROLE_ADMIN', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'SERVICE_CONNECTION_ADMIN', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'SESSION_VARIABLES_ADMIN', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'SET_USER_ID', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'SYSTEM_USER', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'SYSTEM_VARIABLES_ADMIN', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'TABLE_ENCRYPTION_ADMIN', 'YES');
insert into information_schema.USER_PRIVILEGES (GRANTEE, TABLE_CATALOG, PRIVILEGE_TYPE, IS_GRANTABLE) values ('''root''@''localhost''', 'def', 'XA_RECOVER_ADMIN', 'YES');
