insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('British chain (Sears 1922 truncated)', 'LINEAR', 20.116756, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('British foot (Sears 1922 truncated)', 'LINEAR', 0.30479933333333337, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('chain', 'LINEAR', 20.1168, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('yard', 'LINEAR', 0.9144, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('British foot (1936)', 'LINEAR', 0.3048007491, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('British link (Sears 1922 truncated)', 'LINEAR', 0.20116756, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('Gold Coast foot', 'LINEAR', 0.3047997101815088, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('Indian yard (1937)', 'LINEAR', 0.91439523, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('link', 'LINEAR', 0.201168, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('Indian yard', 'LINEAR', 0.9143985307444408, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('Indian yard (1975)', 'LINEAR', 0.9143985, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('Indian yard (1962)', 'LINEAR', 0.9143988, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('Indian foot (1975)', 'LINEAR', 0.3047995, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('Indian foot (1937)', 'LINEAR', 0.30479841, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('Indian foot', 'LINEAR', 0.30479951024814694, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('Indian foot (1962)', 'LINEAR', 0.3047996, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('British foot (1865)', 'LINEAR', 0.30480083333333335, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('British link (Benoit 1895 B)', 'LINEAR', 0.2011678249437587, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('Statute mile', 'LINEAR', 1609.344, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('British chain (Benoit 1895 B)', 'LINEAR', 20.116782494375872, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('British foot (Benoit 1895 B)', 'LINEAR', 0.30479973476327077, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('British link (Benoit 1895 A)', 'LINEAR', 0.201167824, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('British yard (Sears 1922 truncated)', 'LINEAR', 0.914398, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('British yard (Benoit 1895 B)', 'LINEAR', 0.9143992042898124, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('foot', 'LINEAR', 0.3048, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('British foot (Benoit 1895 A)', 'LINEAR', 0.3047997333333333, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('British yard (Benoit 1895 A)', 'LINEAR', 0.9143992, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('British chain (Sears 1922)', 'LINEAR', 20.116765121552632, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('Clarke''s link', 'LINEAR', 0.201166195164, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('Clarke''s chain', 'LINEAR', 20.1166195164, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('British chain (Benoit 1895 A)', 'LINEAR', 20.1167824, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('Clarke''s yard', 'LINEAR', 0.9143917962, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('US survey foot', 'LINEAR', 0.30480060960121924, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('kilometre', 'LINEAR', 1000, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('centimetre', 'LINEAR', 0.01, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('British yard (Sears 1922)', 'LINEAR', 0.9143984146160288, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('US survey mile', 'LINEAR', 1609.3472186944375, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('metre', 'LINEAR', 1, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('US survey link', 'LINEAR', 0.2011684023368047, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('nautical mile', 'LINEAR', 1852, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('British foot (Sears 1922)', 'LINEAR', 0.3047994715386762, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('British link (Sears 1922)', 'LINEAR', 0.2011676512155263, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('fathom', 'LINEAR', 1.8288, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('US survey chain', 'LINEAR', 20.11684023368047, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('German legal metre', 'LINEAR', 1.0000135965, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('Clarke''s foot', 'LINEAR', 0.3047972654, '');
insert into information_schema.ST_UNITS_OF_MEASURE (UNIT_NAME, UNIT_TYPE, CONVERSION_FACTOR, DESCRIPTION) values ('millimetre', 'LINEAR', 0.001, '');
